/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.24).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.AirportsResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-11-25T10:47:55.767Z")

@Validated
@Api(value = "airports", description = "the airports API")
@RequestMapping(value = "/api-v1")
public interface AirportsApi {

    @ApiOperation(value = "List All aiports", nickname = "getAirports", notes = "", response = AirportsResponse.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "KLM", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success response - List of all airports", response = AirportsResponse.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/airports",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<AirportsResponse> getAirports(@ApiParam(value = "the size of the result") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "the page to be selected in the paged response") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "the language, supported ones are nl and en") @Valid @RequestParam(value = "lang", required = false) String lang,@ApiParam(value = "A search term that searches through code, name and description.") @Valid @RequestParam(value = "term", required = false) String term);

}
