/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.24).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Metrics;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-11-25T10:47:55.767Z")

@Validated
@Api(value = "metrics", description = "the metrics API")
@RequestMapping(value = "/api-v1")
public interface MetricsApi {

    @ApiOperation(value = "Get traffic metrics", nickname = "getMetrics", notes = "", response = Metrics.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "KLM", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success response - Get traffic metrics", response = Metrics.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 500, message = "Internal Server Error") })
    @RequestMapping(value = "/metrics",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Metrics> getMetrics();

}
